<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <ul class="nav nav-pills">
                    <li><a class="navbar-brand" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('img/LogoArquitectura.svg') ?>" height="28"/> Postgrados Arquitectura
                        </a></li>
                    <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    <li><a href="<?= $this->url('home') ?>">Mi Perfil</a></li>
                    <li><a href="<?= $this->url('home') ?>">Ingreso de Aspirantes</a></li>
                    <li><a href="<?= $this->url('home') ?>">Periodos de Inscipripción</a></li>
                    <li><a href="<?= $this->url('home') ?>">Problemas de Inscripción</a></li>
                    <li><a href="<?= $this->url('home') ?>">Calendarización</a></li>
                    <li><a href="<?= $this->url('home') ?>">Asignación de Cursos</a></li>
                    <li><a href="<?= $this->url('home') ?>">Asignación Extraordinaria</a></li>
                    <li><a href="<?= $this->url('home') ?>">Cursos Asignados</a></li>
                    <li><a href="<?= $this->url('home') ?>">Asignacion Extemporánea</a></li>
                    <li><a href="<?= $this->url('home') ?>">Reporte General</a></li>
                    <li><a href="<?= $this->url('home') ?>">Reporte de Estudiante</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
<?= $this->content ?>
            <hr>
            <footer>
                <p>Prueba de página de Postgrados de Arquitectura</p>
            </footer>
        </div>
<?= $this->inlineScript() ?>
    </body>
</html>
